.\" Manpage for hostsblock.
.\" Contact jakevanderkolk@gmail.com to correct errors or typos.
.TH man 8 "03 June 2014" "1.0" "hostsblock man page"
.SH NAME
hostsblock \- automatically update HOSTS file entries
.SH SYNOPSIS
hostsblock [\-f config]
.SH DESCRIPTION
Yes
.SH OPTIONS
The nuseradd does not take any options. However, you can supply username.
.SH SEE ALSO
useradd(8), passwd(5), nuseradd.debian(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Jake van der Kolk (jakevanderkolk@gmail.com)
