#!/bin/bash
cuser="${SUDO_USER:-$USER}"
last_update="$(cat /home/"$cuser"/.hostsblock.log | grep 'Hostsblock completed at ' | awk -F ' at ' '{print $2}')"
# confirmation
zenity --question --text "Hostsblock was last updated at<b><i> $last_update </i></b>\n\n<big>Would you like to check online sources and apply any updates now?</big>"
if [ $? = 0 ];
then
# password
sudo_password="$(gksudo --print-pass --description 'hostsblock' -- : 2>/dev/null)"
# check for null entry or cancellation
if [[ ${?} != 0 || -z ${sudo_password} ]]
then
    exit 4
fi
if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
then
    exit 4
fi
# notify
sudo -Sp '' sudo -H -u "$cuser" notify-send "Checking and applying any updates to system hosts file, please wait..." -i gtk-dialog-info -t 3 -u normal <<<"${sudo_password}" &
# proceed to update
sudo -Sp '' sudo /etc/hostsblock/hostsblock.sh -v 3 &>/home/"$cuser"/.hostsblock.log <<<"${sudo_password}"
# append date and time stamp to log
cat <<EOF >> /home/"$cuser"/.hostsblock.log
Hostsblock completed at `date +'%d/%m/%Y %H:%M'`
EOF
# option to view log
sudo -Sp '' sudo -H -u "$cuser" zenity --question --text "Hostsblock completed; would you like to view the log file now?" <<<"${sudo_password}"
if [ $? = 0 ];
then
# display log
sudo -Sp '' sudo -H -u "$cuser" zenity --text-info --filename=/home/"$cuser"/.hostsblock.log --width 500 --height 300 <<<"${sudo_password}"
fi
fi
exit 0
